-- Create user
CREATE USER BMS IDENTIFIED BY BMS;

-- Grant permissions
GRANT CONNECT, RESOURCE TO BMS;
ALTER USER BMS QUOTA UNLIMITED ON USERS;

-- Switch to BMS schema
ALTER SESSION SET CURRENT_SCHEMA = BMS;

-- 1) ACCOUNTS
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID NUMBER(10) NOT NULL,
    ACCOUNT_NUMBER VARCHAR2(20) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    BRANCH_ID NUMBER(10) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20),
    CURRENCY VARCHAR2(3),
    BALANCE NUMBER(15,2),
    STATUS VARCHAR2(20),
    OPEN_DATE DATE,
    CLOSE_DATE DATE,
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNT_ID)
);

-- 2) ATMS
CREATE TABLE ATMS (
    ATM_ID NUMBER(10) NOT NULL,
    ATM_CODE VARCHAR2(10) NOT NULL,
    LOCATION VARCHAR2(200),
    ADDRESS VARCHAR2(200),
    CITY VARCHAR2(50),
    BRANCH_ID NUMBER(10),
    INSTALLATION_DATE DATE,
    STATUS VARCHAR2(20),
    CASH_CAPACITY NUMBER(12,2),
    CURRENT_CASH NUMBER(12,2),
    LAST_REFILL_DATE TIMESTAMP(6),
    MODEL VARCHAR2(50),
    VENDOR VARCHAR2(50),
    CONSTRAINT PK_ATMS PRIMARY KEY (ATM_ID)
);

-- 3) ATM_TRANSACTIONS
CREATE TABLE ATM_TRANSACTIONS (
    TRANSACTION_ID NUMBER(10) NOT NULL,
    ATM_ID NUMBER(10) NOT NULL,
    ACCOUNT_ID NUMBER(10) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(20),
    AMOUNT NUMBER(15,2),
    TRANSACTION_DATE TIMESTAMP(6),
    STATUS VARCHAR2(20),
    CONSTRAINT PK_ATM_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID)
);

-- 4) BRANCHES
CREATE TABLE BRANCHES (
    BRANCH_ID NUMBER(10) NOT NULL,
    BRANCH_CODE VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(100),
    ADDRESS VARCHAR2(200),
    CITY VARCHAR2(50),
    MANAGER_ID NUMBER(10),
    OPEN_DATE DATE,
    STATUS VARCHAR2(20),
    CONSTRAINT PK_BRANCHES PRIMARY KEY (BRANCH_ID)
);

-- 5) CARDS
CREATE TABLE CARDS (
    CARD_ID NUMBER(10) NOT NULL,
    CARD_NUMBER VARCHAR2(20) NOT NULL,
    ACCOUNT_ID NUMBER(10) NOT NULL,
    CARD_TYPE VARCHAR2(20),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    STATUS VARCHAR2(20),
    CVV NUMBER(4),
    CONSTRAINT PK_CARDS PRIMARY KEY (CARD_ID)
);

-- 6) CUSTOMERS
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(10),
    ADDRESS VARCHAR2(200),
    CITY VARCHAR2(50),
    PHONE_NUMBER VARCHAR2(20),
    EMAIL VARCHAR2(100),
    NATIONAL_ID VARCHAR2(20),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

-- 7) CUSTOMER_INVESTMENTS
CREATE TABLE CUSTOMER_INVESTMENTS (
    INVESTMENT_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    PRODUCT_ID NUMBER(10) NOT NULL,
    AMOUNT_INVESTED NUMBER(15,2),
    START_DATE DATE,
    MATURITY_DATE DATE,
    STATUS VARCHAR2(20),
    CONSTRAINT PK_CUSTOMER_INVESTMENTS PRIMARY KEY (INVESTMENT_ID)
);

-- 8) EMPLOYEES
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    POSITION VARCHAR2(50),
    DEPARTMENT VARCHAR2(50),
    BRANCH_ID NUMBER(10),
    HIRE_DATE DATE,
    SALARY NUMBER(15,2),
    STATUS VARCHAR2(20),
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID)
);

-- 9) INVESTMENT_PRODUCTS
CREATE TABLE INVESTMENT_PRODUCTS (
    PRODUCT_ID NUMBER(10) NOT NULL,
    PRODUCT_CODE VARCHAR2(20) NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_TYPE VARCHAR2(30),
    RISK_LEVEL VARCHAR2(20),
    MINIMUM_INVESTMENT NUMBER(12,2),
    EXPECTED_RETURN NUMBER(5,2),
    MATURITY_PERIOD_MONTHS NUMBER(4),
    CURRENCY VARCHAR2(3),
    IS_ACTIVE NUMBER(1),
    LAUNCH_DATE DATE,
    DESCRIPTION CLOB,
    CONSTRAINT PK_INVESTMENT_PRODUCTS PRIMARY KEY (PRODUCT_ID)
);

-- 10) LOANS
CREATE TABLE LOANS (
    LOAN_ID NUMBER(10) NOT NULL,
    LOAN_NUMBER VARCHAR2(20) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    BRANCH_ID NUMBER(10) NOT NULL,
    LOAN_TYPE VARCHAR2(30),
    LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    CURRENCY VARCHAR2(3),
    INTEREST_RATE NUMBER(5,2),
    TERM_MONTHS NUMBER(4),
    MONTHLY_PAYMENT NUMBER(10,2),
    OUTSTANDING_BALANCE NUMBER(15,2),
    APPLICATION_DATE DATE,
    APPROVAL_DATE DATE,
    DISBURSEMENT_DATE DATE,
    MATURITY_DATE DATE,
    STATUS VARCHAR2(20),
    COLLATERAL_TYPE VARCHAR2(50),
    COLLATERAL_VALUE NUMBER(15,2),
    PURPOSE VARCHAR2(100),
    APPROVED_BY VARCHAR2(50),
    LOAN_OFFICER VARCHAR2(50),
    CONSTRAINT PK_LOANS PRIMARY KEY (LOAN_ID)
);

-- 11) LOAN_PAYMENTS
CREATE TABLE LOAN_PAYMENTS (
    PAYMENT_ID NUMBER(10) NOT NULL,
    LOAN_ID NUMBER(10) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    DUE_DATE DATE,
    AMOUNT_DUE NUMBER(10,2),
    AMOUNT_PAID NUMBER(10,2),
    PRINCIPAL_AMOUNT NUMBER(10,2),
    INTEREST_AMOUNT NUMBER(10,2),
    LATE_FEE NUMBER(8,2),
    PAYMENT_STATUS VARCHAR2(20),
    PAYMENT_METHOD VARCHAR2(30),
    RECEIPT_NUMBER VARCHAR2(50),
    PROCESSED_BY VARCHAR2(50),
    CONSTRAINT PK_LOAN_PAYMENTS PRIMARY KEY (PAYMENT_ID)
);

-- 12) TRANSACTIONS
CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID NUMBER(10) NOT NULL,
    TRANSACTION_REFERENCE VARCHAR2(50) NOT NULL,
    ACCOUNT_ID NUMBER(10) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(30) NOT NULL,
    TRANSACTION_CATEGORY VARCHAR2(30),
    AMOUNT NUMBER(15,2) NOT NULL,
    CURRENCY VARCHAR2(3),
    TRANSACTION_DATE TIMESTAMP(6),
    VALUE_DATE DATE,
    DESCRIPTION VARCHAR2(200),
    REFERENCE_NUMBER VARCHAR2(50),
    CHANNEL VARCHAR2(20),
    LOCATION VARCHAR2(100),
    STATUS VARCHAR2(20),
    BALANCE_AFTER NUMBER(15,2),
    FEES NUMBER(10,2),
    EXCHANGE_RATE NUMBER(10,4),
    MERCHANT_NAME VARCHAR2(100),
    MERCHANT_CATEGORY VARCHAR2(50),
    PROCESSED_BY VARCHAR2(50),
    AUTHORIZED_BY VARCHAR2(50),
    CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID)
);
